helpop:
  enabled: true
webhooks:
  helpop:
  - url: https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}
    parameters:
      embeds:
      - color: '15158332'
        title: '{sender_name} napisał'
        description: '{message}'
  - url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
    parameters:
      color: '#e74c3c'
      fields:
      - title: '{sender_name} napisał'
        value: '{message}'
        short: false
      fallback: '{sender_name} napisał {message}'
messages:
  commands:
    helpop:
      correct_use: '&cPoprawne uzycie: &e/helpop <wiadomosc>'
      toggle:
        enable: '&cHelpop został włączony!'
        disable: '&cHelpop został wyłączony!'
      disabled: '&cHelpop jest aktualnie wyłączony!'
      message_style:
        receiver: '&4[HelpOp] &c{sender_name} &r>> {message}'
        receiver_server: "&4[HelpOp] ({server_name}) &c{sender_name} &r>> {message}"
        sender: '&c{sender_name}&r> {message}'