main: pl.javatar.minecraft.vwhelpop.HelpopPlugin
name: vw-helpop
version: "${version} (#${ext.git['git.commit.id.abbrev']})"
author: tirex

softdepend:
  - "goxy-pubsub"

commands:
  helpop:
    permission: helpop.user